[package]
name = "toons"
version = "0.5.3"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "toons"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "*"
